# ami            = "<ami_id>"
# instance_type  = "t2.micro"
# instance_name  = "Webserver-chirag"
# bucket_name    = "<bucket name>"
# key_pair       = "<key_pair_name>"
# ec2_iam_role_arn = "arn:aws:iam::021891610828:role/EC2-S3-Role" 
# vpc_cidr_ip = "<vpc_cidr>"
# pub_subnet_cidr_ip = "<pub_subnet_cidr>"
