---
- name: Kubernetes Node Setup
  hosts: all
  become: yes
  roles:
    - k8s_nodes

- name: Setup Kubernetes Master Nodes
  hosts: master_nodes
  become: yes
  roles:
    - k8s_master

- name: Setup Kubernetes Worker Nodes
  hosts: worker_nodes
  become: yes
  roles:
    - k8s_worker