---
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Update and upgrade all packages to the latest version
  apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - gpg
      - python3-apt
      - software-properties-common
      - docker.io

- name: Enable and start Docker services
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - docker.service
    - containerd.service


# Installing Kubeadm, kubectl and kubelet

- name: Ensure /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
    
- name: Get Kubernetes package key
  shell: curl -fsSL {{ k8s_url_apt_key }} | gpg --dearmor -o {{ k8s_gpgpath }}
  args:
    creates: "{{ k8s_gpgpath }}"
 
- name: Install Kubernetes repository
  apt_repository:
    filename: kubernetes
    repo: "deb [signed-by={{ k8s_gpgpath }}] {{ k8s_repository }} /"
 

- name: Update APT package index
  apt:
    update_cache: yes

- name: Install Kubernetes components
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Hold Kubernetes packages to prevent upgrades
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Create .kube directory
  file:
    path: /home/{{ ansible_env.USER }}/.kube
    state: directory
    mode: '0700'

- name: Copy admin.conf to .kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_env.USER }}/.kube/config
    remote_src: yes

- name: Change ownership of the kube config file
  file:
    path: "/home/{{ ansible_env.USER }}/.kube/config"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0644'

- name: Disable swap (required by kubelet)
  command: swapoff -a

- name: Disable swap in fstab
  replace:
    path: /etc/fstab
    regexp: '^\s*([^#\s]\S+)\s+\S+\s+swap\s+\S+\s+(.*)$'
    replace: '# \1 swap \2'

