---
# tasks file for roles/Mysql
- name: Installing Mysql  and dependencies
  package:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - mysql-server
    - mysql-client 
    - python3-mysqldb
    - libmysqlclient-dev
  become: yes

- name: start and enable mysql service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Set MySQL root password
  mysql_user:
    name: root
    password: "password"
    host: all
    state: present
  become: yes

- name: Remove anonymous MySQL user
  mysql_user:
    name: ''
    host: all
    state: absent
    login_user: root
    login_password: "{{ db_root_password }}"
  become: yes

- name: Remove MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ db_root_password }}"
  become: yes

- name: Create MySQL database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root
    login_password: "{{ db_root_password }}"
  become: yes

- name: Create MySQL user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ db_root_password }}"
  become: yes